apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: november-flask-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: november-flask-app
