apiVersion: v1
kind: Service
metadata:
  name: november-flask-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: november-flask-app
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30080
